### ISSUE TITLE
react-native-contacts fork

### ISSUE THREAD

**Issue by rt2zz** [JeanLebrument/react-native-contacts-rx#3]
I see you have a react-native-contacts fork which cleans up the code a bit and adds more details. It looks great. questions:

Is there anything holding you back from submitting a PR? The only thing I can think of is the need to mirror these changes in android.

If you are interested in playing a role in mantaining react-native-contacts I would be happy to add you as a collaborator. We could also transfer ownership to a different organization, or to your github if you like.

Zack

**Comment by JeanLebrument** [comment]
Hi Zack,

Thanks for reaching out! I forked your repo because I needed to fetch more data from the contacts iOS API. I planned to submit a pull request but I wanted to clean my code first. 

For now I'm using `APAddressBook` which is great to retrieve data but I had to serialize the `APContact` model myself because there is no such a feature on the library for now. https://github.com/Alterplay/APAddressBook/issues/108

So I wanted to first create a pod `APContact+EasyMapping` as proposed by @belkevich in the above ticket and then integrate this to my code in this repository before submitting a pull request. 

I'm quite busy these days but I would be glad to help you to maintain `react-native-contacts` as a collaborator! I think it's more legitimate that you keep the ownership of this repository since you're the creator of this package. 

Here are my roadmap proposal to improve `react-native-contacts` package for the iOS part: 
- Create `APContact+EasyMapping` pod and integrate it to `react-native-contacts` package. https://github.com/Alterplay/APAddressBook/issues/108
- Add the update feature to `APAddressBook` pod and then add it to `react-native-contacts` https://github.com/Alterplay/APAddressBook/issues/107
- Add the delete feature to `APAddressBook` pod and then add it to `react-native-contacts` https://github.com/Alterplay/APAddressBook/issues/67

After this work done, the iOS part of `react-native-contacts` would be net, fully functional and won't reinvent the wheel! :+1: 

What do you think about it?

**Comment by rt2zz** [comment]
sounds appealing. working with AddressBook is suck x.x

My concern however is that many react-native users do not use pods (e.g. myself :fearful:) Is there anyway to embed APAdressBook into our library without requiring any user linking or pod installation?

**Comment by JeanLebrument** [comment]
Cool!

Yes of course, cocoapods is a convenient tool to install 3rd-party libraries but it's not mandatory. 
The final user won't have to worry about `APAdressBook` since it will be directly provided with our package. He won't notice that we're using a 3rd-party library.

I will work on the `APContact+EasyMapping` soon and will submit a pull request when it will be integrated  on my fork.

**Comment by rt2zz** [comment]
cool deal :+1:
